title: Alex R
author: pro-panda
subtitle: Another tech focused blog

url: "https://alexreido.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: ""
footer_text: "All opinions my own"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

excerpt_separator: ""

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://alexreido.github.io/CV.pdf"
